### ISSUE TITLE
Inform Flatpak users that some components/programs may fail to install due to missing `--allow=devel` permission

### ISSUE THREAD

**Issue by guihkx** [bottlesdevs/documentation#12]
Also be clear about the implications of enabling such permission (i.e. potential sandbox breakage).

Details: https://github.com/flathub/com.usebottles.bottles/pull/272
Also: https://github.com/bottlesdevs/Bottles/issues/864

**Comment by guihkx** [comment]
Out of curiosity, I asked about this permission in the #flatpak room on IRC, here are some screenshots of the conversation:

![image](https://user-images.githubusercontent.com/626206/148845512-f06fb3f1-4567-4f16-bbd9-8d3a761c816f.png)

![image](https://user-images.githubusercontent.com/626206/148845795-dc56e647-da02-4429-abb0-c550067f5e9f.png)

**Comment by mirkobrombin** [comment]
So there is no risk to break the sandbox but maybe other btrace related problems (?) Idk if enabling this will result is somewhat exposure, despite the programs will still not able to escape to the sandbox, they can still “corrupt” other processes (?)

**Comment by guihkx** [comment]
>So there is no risk to break the sandbox

From what I could summarize from the conversation, *if* there's a sandbox escape somehow using ptrace, it's unexpected and should be considered a security bug.

>they can still “corrupt” other processes in the same namespace (?)

I assume this is only true for native Linux programs. In my understanding, programs running on Wine aren't aware of ptrace() at all. However, [Wine itself uses ptrace](https://github.com/wine-mirror/wine/search?q=ptrace).

Steam and Lutris have been using this permission for years (Lutris because of Wine programs, and Steam initially because some native games from Feral were using ptrace, and later because of Proton), and no sandbox escaping have been found in the wild yet.

In the end, I think what gasinvein said there pretty much sums it up:

>I can't say it's still secured on the same level, but I don't know a trivial (or any) way to escape de sandbox using ptrace either

**Comment by ThomChroma** [comment]
I just read the discussion about dotnet35 and realise that missing this permission also prevented the EVE Online launcher to show for me, with these errors:

```
E0110 23:03:19.170000000   520 ssl_transport_security.cc:667] Could not set ephemeral ECDH key.
E0110 23:03:19.170000000   520 security_connector.cc:1062] Handshaker factory creation failed with TSI_INTERNAL_ERROR.
E0110 23:03:19.170000000   520 secure_channel_create.cc:121] Failed to create secure subchannel for secure name 'elg-live.evetech.net'
E0110 23:03:19.170000000   520 secure_channel_create.cc:154] Failed to create subchannel arguments during subchannel creation.
E0110 23:03:19.171000000   520 ssl_transport_security.cc:667] Could not set ephemeral ECDH key.
E0110 23:03:19.171000000   520 security_connector.cc:1062] Handshaker factory creation failed with TSI_INTERNAL_ERROR.
E0110 23:03:19.171000000   520 secure_channel_create.cc:121] Failed to create secure subchannel for secure name 'elg-live.evetech.net'
E0110 23:03:19.171000000   520 secure_channel_create.cc:154] Failed to create subchannel arguments during subchannel creation.
E0110 23:03:19.171000000   520 ssl_transport_security.cc:667] Could not set ephemeral ECDH key.
E0110 23:03:19.171000000   520 security_connector.cc:1062] Handshaker factory creation failed with TSI_INTERNAL_ERROR.
E0110 23:03:19.171000000   520 secure_channel_create.cc:121] Failed to create secure subchannel for secure name 'elg-live.evetech.net'
E0110 23:03:19.171000000   520 secure_channel_create.cc:154] Failed to create subchannel arguments during subchannel creation.
```
Actually, unable to contact the server, the launcher stays minimized and empty. Enabling the permission solves the problem. So unfortunately it seems to be essential for some games too… That's probably why they all use it.

**Comment by mirkobrombin** [comment]
I’ll consider to provide such flag by default on Bottles. At least we can still remove it if problems appear

**Comment by mirkobrombin** [comment]
We are also consider using flatpak spawn portal to isolate each bottles and give them specific permissions but seems like the devel flag is not supported. Also I’ve not deeply investigating on it and maybe it does not do what we supposed to 😅
https://docs.flatpak.org/en/latest/portal-api-reference.html#gdbus-method-org-freedesktop-portal-Flatpak.Spawn

**Comment by guihkx** [comment]
That sounds pretty cool! I think "sub-sandboxing" is what Proton does right now when you run Steam via Flatpak. https://github.com/flathub/com.valvesoftware.Steam/issues/642
