### ISSUE TITLE
Migrate from gitboot to other static site builder

### ISSUE THREAD

**Issue by tiziodcaio** [bottlesdevs/documentation#18]
I think gitbook sucks, cuz it's closed source and limitated. If you want I can migrate the repo to [vuepress](https://vuepress.github.io) ... If you are intersted I'll be able to do a Pull Request

**Comment by mirkobrombin** [comment]
Ehm, where should I host it? 😅  

Btw https://github.com/GitbookIO/gitbook 👀

**Comment by tiziodcaio** [comment]
Til... Duh sorry idk that... 😢 Btw what do you mean for hosting? How to deploy or how to migrate the repository?

**Comment by mirkobrombin** [comment]
Deploy. Btw I feel very comfortable with GitBook and I don't think I will migrate it to other services or platforms :D

**Comment by tiziodcaio** [comment]
Sure, happy with this. Happy for how's going your project... Good afternoon
